/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BancaRouteImport } from './routes/banca'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SantuarioIndexRouteImport } from './routes/santuario.index'
import { Route as RevistaIndexRouteImport } from './routes/revista.index'
import { Route as SantuarioSlugRouteImport } from './routes/santuario.$slug'
import { Route as RevistaIdRouteImport } from './routes/revista.$id'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BancaRoute = BancaRouteImport.update({
  id: '/banca',
  path: '/banca',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SantuarioIndexRoute = SantuarioIndexRouteImport.update({
  id: '/santuario/',
  path: '/santuario/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevistaIndexRoute = RevistaIndexRouteImport.update({
  id: '/revista/',
  path: '/revista/',
  getParentRoute: () => rootRouteImport,
} as any)
const SantuarioSlugRoute = SantuarioSlugRouteImport.update({
  id: '/santuario/$slug',
  path: '/santuario/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RevistaIdRoute = RevistaIdRouteImport.update({
  id: '/revista/$id',
  path: '/revista/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/banca': typeof BancaRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/revista/$id': typeof RevistaIdRoute
  '/santuario/$slug': typeof SantuarioSlugRoute
  '/revista/': typeof RevistaIndexRoute
  '/santuario/': typeof SantuarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/banca': typeof BancaRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/revista/$id': typeof RevistaIdRoute
  '/santuario/$slug': typeof SantuarioSlugRoute
  '/revista': typeof RevistaIndexRoute
  '/santuario': typeof SantuarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/banca': typeof BancaRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/revista/$id': typeof RevistaIdRoute
  '/santuario/$slug': typeof SantuarioSlugRoute
  '/revista/': typeof RevistaIndexRoute
  '/santuario/': typeof SantuarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album'
    | '/banca'
    | '/login'
    | '/perfil'
    | '/registro'
    | '/revista/$id'
    | '/santuario/$slug'
    | '/revista/'
    | '/santuario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album'
    | '/banca'
    | '/login'
    | '/perfil'
    | '/registro'
    | '/revista/$id'
    | '/santuario/$slug'
    | '/revista'
    | '/santuario'
  id:
    | '__root__'
    | '/'
    | '/album'
    | '/banca'
    | '/login'
    | '/perfil'
    | '/registro'
    | '/revista/$id'
    | '/santuario/$slug'
    | '/revista/'
    | '/santuario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRoute
  BancaRoute: typeof BancaRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RegistroRoute: typeof RegistroRoute
  RevistaIdRoute: typeof RevistaIdRoute
  SantuarioSlugRoute: typeof SantuarioSlugRoute
  RevistaIndexRoute: typeof RevistaIndexRoute
  SantuarioIndexRoute: typeof SantuarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banca': {
      id: '/banca'
      path: '/banca'
      fullPath: '/banca'
      preLoaderRoute: typeof BancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santuario/': {
      id: '/santuario/'
      path: '/santuario'
      fullPath: '/santuario/'
      preLoaderRoute: typeof SantuarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revista/': {
      id: '/revista/'
      path: '/revista'
      fullPath: '/revista/'
      preLoaderRoute: typeof RevistaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santuario/$slug': {
      id: '/santuario/$slug'
      path: '/santuario/$slug'
      fullPath: '/santuario/$slug'
      preLoaderRoute: typeof SantuarioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revista/$id': {
      id: '/revista/$id'
      path: '/revista/$id'
      fullPath: '/revista/$id'
      preLoaderRoute: typeof RevistaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRoute,
  BancaRoute: BancaRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RegistroRoute: RegistroRoute,
  RevistaIdRoute: RevistaIdRoute,
  SantuarioSlugRoute: SantuarioSlugRoute,
  RevistaIndexRoute: RevistaIndexRoute,
  SantuarioIndexRoute: SantuarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
