/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as BancaRouteImport } from './routes/banca'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SantuarioIndexRouteImport } from './routes/santuario.index'
import { Route as RevistaIndexRouteImport } from './routes/revista.index'
import { Route as ComunidadesIndexRouteImport } from './routes/comunidades.index'
import { Route as SantuarioSlugRouteImport } from './routes/santuario.$slug'
import { Route as RevistaIdRouteImport } from './routes/revista.$id'
import { Route as ComunidadesSlugRouteImport } from './routes/comunidades.$slug'
import { Route as ApiPublicBotProfileRouteImport } from './routes/api/public/bot.profile'
import { Route as ApiPublicBotDiscordLinkRouteImport } from './routes/api/public/bot.discord-link'
import { Route as ApiPublicBotCardsGrantRouteImport } from './routes/api/public/bot.cards-grant'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const BancaRoute = BancaRouteImport.update({
  id: '/banca',
  path: '/banca',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SantuarioIndexRoute = SantuarioIndexRouteImport.update({
  id: '/santuario/',
  path: '/santuario/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevistaIndexRoute = RevistaIndexRouteImport.update({
  id: '/revista/',
  path: '/revista/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesIndexRoute = ComunidadesIndexRouteImport.update({
  id: '/comunidades/',
  path: '/comunidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const SantuarioSlugRoute = SantuarioSlugRouteImport.update({
  id: '/santuario/$slug',
  path: '/santuario/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RevistaIdRoute = RevistaIdRouteImport.update({
  id: '/revista/$id',
  path: '/revista/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesSlugRoute = ComunidadesSlugRouteImport.update({
  id: '/comunidades/$slug',
  path: '/comunidades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotProfileRoute = ApiPublicBotProfileRouteImport.update({
  id: '/api/public/bot/profile',
  path: '/api/public/bot/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotDiscordLinkRoute = ApiPublicBotDiscordLinkRouteImport.update({
  id: '/api/public/bot/discord-link',
  path: '/api/public/bot/discord-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotCardsGrantRoute = ApiPublicBotCardsGrantRouteImport.update({
  id: '/api/public/bot/cards-grant',
  path: '/api/public/bot/cards-grant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/album': typeof AlbumRoute
  '/banca': typeof BancaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/revista/$id': typeof RevistaIdRoute
  '/santuario/$slug': typeof SantuarioSlugRoute
  '/comunidades/': typeof ComunidadesIndexRoute
  '/revista/': typeof RevistaIndexRoute
  '/santuario/': typeof SantuarioIndexRoute
  '/api/public/bot/cards-grant': typeof ApiPublicBotCardsGrantRoute
  '/api/public/bot/discord-link': typeof ApiPublicBotDiscordLinkRoute
  '/api/public/bot/profile': typeof ApiPublicBotProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/album': typeof AlbumRoute
  '/banca': typeof BancaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/revista/$id': typeof RevistaIdRoute
  '/santuario/$slug': typeof SantuarioSlugRoute
  '/comunidades': typeof ComunidadesIndexRoute
  '/revista': typeof RevistaIndexRoute
  '/santuario': typeof SantuarioIndexRoute
  '/api/public/bot/cards-grant': typeof ApiPublicBotCardsGrantRoute
  '/api/public/bot/discord-link': typeof ApiPublicBotDiscordLinkRoute
  '/api/public/bot/profile': typeof ApiPublicBotProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/album': typeof AlbumRoute
  '/banca': typeof BancaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/perfil': typeof PerfilRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registro': typeof RegistroRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/revista/$id': typeof RevistaIdRoute
  '/santuario/$slug': typeof SantuarioSlugRoute
  '/comunidades/': typeof ComunidadesIndexRoute
  '/revista/': typeof RevistaIndexRoute
  '/santuario/': typeof SantuarioIndexRoute
  '/api/public/bot/cards-grant': typeof ApiPublicBotCardsGrantRoute
  '/api/public/bot/discord-link': typeof ApiPublicBotDiscordLinkRoute
  '/api/public/bot/profile': typeof ApiPublicBotProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/album'
    | '/banca'
    | '/esqueci-senha'
    | '/feed'
    | '/login'
    | '/mensagens'
    | '/perfil'
    | '/redefinir-senha'
    | '/registro'
    | '/comunidades/$slug'
    | '/revista/$id'
    | '/santuario/$slug'
    | '/comunidades/'
    | '/revista/'
    | '/santuario/'
    | '/api/public/bot/cards-grant'
    | '/api/public/bot/discord-link'
    | '/api/public/bot/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/album'
    | '/banca'
    | '/esqueci-senha'
    | '/feed'
    | '/login'
    | '/mensagens'
    | '/perfil'
    | '/redefinir-senha'
    | '/registro'
    | '/comunidades/$slug'
    | '/revista/$id'
    | '/santuario/$slug'
    | '/comunidades'
    | '/revista'
    | '/santuario'
    | '/api/public/bot/cards-grant'
    | '/api/public/bot/discord-link'
    | '/api/public/bot/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/album'
    | '/banca'
    | '/esqueci-senha'
    | '/feed'
    | '/login'
    | '/mensagens'
    | '/perfil'
    | '/redefinir-senha'
    | '/registro'
    | '/comunidades/$slug'
    | '/revista/$id'
    | '/santuario/$slug'
    | '/comunidades/'
    | '/revista/'
    | '/santuario/'
    | '/api/public/bot/cards-grant'
    | '/api/public/bot/discord-link'
    | '/api/public/bot/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlbumRoute: typeof AlbumRoute
  BancaRoute: typeof BancaRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  MensagensRoute: typeof MensagensRoute
  PerfilRoute: typeof PerfilRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RegistroRoute: typeof RegistroRoute
  ComunidadesSlugRoute: typeof ComunidadesSlugRoute
  RevistaIdRoute: typeof RevistaIdRoute
  SantuarioSlugRoute: typeof SantuarioSlugRoute
  ComunidadesIndexRoute: typeof ComunidadesIndexRoute
  RevistaIndexRoute: typeof RevistaIndexRoute
  SantuarioIndexRoute: typeof SantuarioIndexRoute
  ApiPublicBotCardsGrantRoute: typeof ApiPublicBotCardsGrantRoute
  ApiPublicBotDiscordLinkRoute: typeof ApiPublicBotDiscordLinkRoute
  ApiPublicBotProfileRoute: typeof ApiPublicBotProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banca': {
      id: '/banca'
      path: '/banca'
      fullPath: '/banca'
      preLoaderRoute: typeof BancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santuario/': {
      id: '/santuario/'
      path: '/santuario'
      fullPath: '/santuario/'
      preLoaderRoute: typeof SantuarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revista/': {
      id: '/revista/'
      path: '/revista'
      fullPath: '/revista/'
      preLoaderRoute: typeof RevistaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/': {
      id: '/comunidades/'
      path: '/comunidades'
      fullPath: '/comunidades/'
      preLoaderRoute: typeof ComunidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santuario/$slug': {
      id: '/santuario/$slug'
      path: '/santuario/$slug'
      fullPath: '/santuario/$slug'
      preLoaderRoute: typeof SantuarioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revista/$id': {
      id: '/revista/$id'
      path: '/revista/$id'
      fullPath: '/revista/$id'
      preLoaderRoute: typeof RevistaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades/$slug': {
      id: '/comunidades/$slug'
      path: '/comunidades/$slug'
      fullPath: '/comunidades/$slug'
      preLoaderRoute: typeof ComunidadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/profile': {
      id: '/api/public/bot/profile'
      path: '/api/public/bot/profile'
      fullPath: '/api/public/bot/profile'
      preLoaderRoute: typeof ApiPublicBotProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/discord-link': {
      id: '/api/public/bot/discord-link'
      path: '/api/public/bot/discord-link'
      fullPath: '/api/public/bot/discord-link'
      preLoaderRoute: typeof ApiPublicBotDiscordLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/cards-grant': {
      id: '/api/public/bot/cards-grant'
      path: '/api/public/bot/cards-grant'
      fullPath: '/api/public/bot/cards-grant'
      preLoaderRoute: typeof ApiPublicBotCardsGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlbumRoute: AlbumRoute,
  BancaRoute: BancaRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  MensagensRoute: MensagensRoute,
  PerfilRoute: PerfilRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RegistroRoute: RegistroRoute,
  ComunidadesSlugRoute: ComunidadesSlugRoute,
  RevistaIdRoute: RevistaIdRoute,
  SantuarioSlugRoute: SantuarioSlugRoute,
  ComunidadesIndexRoute: ComunidadesIndexRoute,
  RevistaIndexRoute: RevistaIndexRoute,
  SantuarioIndexRoute: SantuarioIndexRoute,
  ApiPublicBotCardsGrantRoute: ApiPublicBotCardsGrantRoute,
  ApiPublicBotDiscordLinkRoute: ApiPublicBotDiscordLinkRoute,
  ApiPublicBotProfileRoute: ApiPublicBotProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
